# Generated by Django 5.2.5 on 2025-09-05 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='производитель')),
                ('country', models.CharField(max_length=100, verbose_name='страна')),
                ('website', models.URLField(blank=True, verbose_name='вебсайт')),
            ],
            options={
                'verbose_name': 'производителя',
                'verbose_name_plural': 'Производители',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255, verbose_name='модель')),
                ('engine_volume', models.IntegerField(blank=True, null=True, verbose_name='двигатель')),
                ('year', models.IntegerField(default=20, verbose_name='год выпуска')),
                ('file', models.FileField(upload_to='uploads/', verbose_name='файл')),
                ('file_preview', models.ImageField(blank=True, null=True, upload_to='previews/', verbose_name='превью')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuals.factory', verbose_name='бренд')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
                'ordering': ['factory'],
            },
        ),
    ]
