# Generated by Django 5.2.5 on 2025-09-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='image',
            field=models.ImageField(null=True, upload_to='factory_images/', verbose_name='изображение'),
        ),
    ]
